zabbix_export:
  version: '5.4'
  date: '2021-11-09T05:04:49Z'
  groups:
    -
      uuid: d5136ee100834d539098227414b6eef9
      name: CISCO-ESA
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
  templates:
    -
      uuid: 61f6e0af124a445e911cdc77d065c983
      template: ESA-CISCO
      name: ESA-CISCO
      description: |
        ## Description
        
        Cisco IronPort Email and Web Security
        
        ## Overview
        
        -- *****************************************************************  
        -- ASYNCOS-MAIL-MIB  
        -- Copyright (c) 2005-2011 by Cisco Systems, Inc.  
        -- All rights reserved.  
        -- Cisco IronPort Email and Web Security Customer Service  
        -- *****************************************************************
        
        
        Adicione as MIBs no servidor de monitoramento antes de executar o template nos appliances 
        
        
        <https://www.cisco.com/web/ironport/tools/email/ASYNCOS-MAIL-MIB.txt>  
        <https://www.cisco.com/web/ironport/tools/email/IRONPORT-SMI.txt>
        
        
        
        ## Author
        
        Lauro de Paula
        
        
      groups:
        -
          name: CISCO-ESA
        -
          name: Templates
      items:
        -
          uuid: c589419961c042a181de5cc133afe57a
          name: asyncOSMailObjects
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.27.0
          key: asyncOSMailObjects.27.0
          delay: 180s
          trends: '0'
          value_type: TEXT
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 61d25f05feeb4a478e5fd66bf1756d51
          name: mailTransferThreads
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.20.0
          key: mailTransferThreads.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 0bb5a01782f24e17aea75b817edb3efa
          name: memoryAvailabilityStatus
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.7.0
          key: memoryAvailabilityStatus.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          valuemap:
            name: ESA-memoryAvailabilityStatus
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: b3d5cd420c0a4d7d82496cfaae25c547
          name: oldestMessageAge
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.14.0
          key: oldestMessageAge.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 48f2e34bf4be427099148f7cff614941
          name: openFilesOrSockets
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.19.0
          key: openFilesOrSockets.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 4f77e85c04e8489388a4124228f5bb1e
          name: outstandingDNSRequests
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.15.0
          key: outstandingDNSRequests.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: d4e731e899154832a600bda089bb153f
          name: pendingDNSRequests
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.16.0
          key: pendingDNSRequests.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 148642d5b36143aeaaeacf09d5d06fc4
          name: perCentCPUUtilization
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.2.0
          key: perCentCPUUtilization.0
          delay: 45s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
          triggers:
            -
              uuid: 2d42c0ca49aa4059bb404bd3a652e35d
              expression: 'avg(/ESA-CISCO/perCentCPUUtilization.0,5m)>50'
              name: 'perCentCPUUtilization 50% {HOST.NAME}'
              priority: WARNING
            -
              uuid: d812eaf2b40649df96a99f9758bed5b5
              expression: 'avg(/ESA-CISCO/perCentCPUUtilization.0,5m)>70'
              name: 'perCentCPUUtilization 70% {HOST.NAME}'
              priority: AVERAGE
            -
              uuid: 014358975f6a4925a2e5311d88409fb4
              expression: 'avg(/ESA-CISCO/perCentCPUUtilization.0,5m)>90'
              name: 'perCentCPUUtilization 90% {HOST.NAME}'
              priority: HIGH
        -
          uuid: d345390104e543c0868857a7a14f5c60
          name: perCentDiskIOUtilization
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.3.0
          key: perCentDiskIOUtilization.0
          delay: 45s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 057653b125a5460191ca68c0183a1b4b
          name: perCentMemoryUtilization
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.1.0
          key: perCentMemoryUtilization.0
          delay: 45s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
          triggers:
            -
              uuid: dbba9ec54cd14cb6abe3f57adc20fa4c
              expression: 'avg(/ESA-CISCO/perCentMemoryUtilization.0,5m)>50'
              name: 'perCentMemoryUtilization 50% {HOST.NAME}'
              priority: WARNING
            -
              uuid: e65dd6788a374063b3c30dc981467819
              expression: 'avg(/ESA-CISCO/perCentMemoryUtilization.0,5m)>70'
              name: 'perCentMemoryUtilization 70% {HOST.NAME}'
              priority: AVERAGE
            -
              uuid: 09ffcbbf19b546c58c6799aa597d7d3f
              expression: 'avg(/ESA-CISCO/perCentMemoryUtilization.0,5m)>90'
              name: 'perCentMemoryUtilization 90% {HOST.NAME}'
              priority: HIGH
        -
          uuid: bbc6e81c30704391be758596a6ecf16c
          name: perCentQueueUtilization
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.4.0
          key: perCentQueueUtilization.0
          delay: 30s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: 004c3ce8a8dd4c91b2bbd196268cfc4f
          name: queueAvailabilityStatus
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.5.0
          key: queueAvailabilityStatus.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          valuemap:
            name: ESA-queueAvailabilityStatus
          tags:
            -
              tag: Application
              value: EmailSecurity
        -
          uuid: c35eeb73521b478c88bf2fb3bf399065
          name: resourceConservationReason
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.15497.1.1.1.6.0
          key: resourceConservationReason.0
          delay: 180s
          description: |
            -- *****************************************************************
            -- ASYNCOS-MAIL-MIB
            -- Copyright (c) 2005-2011 by Cisco Systems, Inc.
            -- All rights reserved.
            -- Cisco IronPort Email and Web Security Customer Service
            -- *****************************************************************
          valuemap:
            name: ESA-resourceConservationReason
          tags:
            -
              tag: Application
              value: EmailSecurity
      discovery_rules:
        -
          uuid: c68ae251df2e4d959f7f7120717bf6d8
          name: keyDescription
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#SNMPVALUE},1.3.6.1.4.1.15497.1.1.1.12.1.2]'
          key: keyDescription
          delay: 1h
          item_prototypes:
            -
              uuid: 04a3c7b78b94420ea450cacde510a992
              name: 'keyDescription $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.12.1.2.{#SNMPINDEX}'
              key: 'keyDescription[{#SNMPVALUE}]'
              delay: 3h
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: EmailSecurity
            -
              uuid: 89b9a8c11c9e40a4829ac59b44e76706
              name: 'keyIsPerpetual $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.12.1.3.{#SNMPINDEX}'
              key: 'keyIsPerpetual[{#SNMPVALUE}]'
              delay: 3h
              tags:
                -
                  tag: Application
                  value: EmailSecurity
            -
              uuid: 9330811fa4a8471c8e5b775f4e66a8bb
              name: 'keySecondsUntilExpire $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.12.1.4.{#SNMPINDEX}'
              key: 'keySecondsUntilExpire[{#SNMPVALUE}]'
              delay: 3h
              units: s
              tags:
                -
                  tag: Application
                  value: EmailSecurity
        -
          uuid: f5a1df45e0f445eaa249a3ff7c4ce09c
          name: updateServiceName
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#SNMPVALUE},1.3.6.1.4.1.15497.1.1.1.13.1.2]'
          key: updateServiceName
          delay: 1h
          item_prototypes:
            -
              uuid: dd4143c7702f4a838d15c509daecf2a5
              name: 'updateFailures $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.13.1.4.{#SNMPINDEX}'
              key: 'updateFailures[{#SNMPVALUE}]'
              delay: 2h
              tags:
                -
                  tag: Application
                  value: EmailSecurity
            -
              uuid: e694e608be8c4b6e84e5411d1add147c
              name: 'updateServiceName $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.13.1.2.{#SNMPINDEX}'
              key: 'updateServiceName[{#SNMPVALUE}]'
              delay: 2h
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: EmailSecurity
            -
              uuid: 53e6e173e7ba409e8dab2c06bf3aad67
              name: 'updates $1'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.15497.1.1.1.13.1.3.{#SNMPINDEX}'
              key: 'updates[{#SNMPVALUE}]'
              delay: 2h
              tags:
                -
                  tag: Application
                  value: EmailSecurity
      valuemaps:
        -
          uuid: ed2d4803c6fa40ee914f85e39c6ec9ed
          name: ESA-memoryAvailabilityStatus
          mappings:
            -
              value: '1'
              newvalue: memoryAvailable
            -
              value: '2'
              newvalue: memoryShortage
            -
              value: '3'
              newvalue: memoryFull
        -
          uuid: 6a0a5dad4885470b86457e11654f607e
          name: ESA-queueAvailabilityStatus
          mappings:
            -
              value: '1'
              newvalue: queueSpaceAvailable
            -
              value: '2'
              newvalue: queueSpaceShortage
            -
              value: '3'
              newvalue: queueFull
        -
          uuid: f3e29b2336b2496fb6bc45a8624db1e4
          name: ESA-resourceConservationReason
          mappings:
            -
              value: '1'
              newvalue: noResourceConservation
            -
              value: '2'
              newvalue: memoryShortage
            -
              value: '3'
              newvalue: queueSpaceShortage
            -
              value: '4'
              newvalue: queueFull
