name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      zabbix:
        image: zabbix/zabbix-appliance
        env:
          PHP_TZ: "Europe/Riga"
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v2

      - name: Import templates
        run: |
          python -m pip install py-zabbix
          sleep 30
          find . -type f -name "*.yaml" | sort | xargs -n 1 echo
          
