name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      zabbix:
        image: zabbix/zabbix-appliance
        env:
          PHP_TZ: "Europe/Riga"
        options: >-
          --health-cmd "systemctl is-active nginx"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v2

      - name: Check localhost
        run: |
          curl localhost
