name: Template validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres-server:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server:
        image: zabbix/zabbix-server-pgsql
        env:
          DB_SERVER_HOST: postgres-server
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web:
        image: zabbix/zabbix-web-nginx-pgsql
        ports:
          - "80:80"
        env:
          DB_SERVER_HOST: postgres-server
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

    steps:
      - uses: actions/checkout@v2
      - name: Wait for Zabbix API
        run: |
          python -m pip install py-zabbix
          ./.github/workflows/check.py
