name: Update README.md

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install depends
        run: python -m pip install xmltodict

      - name: Run update script
        run: ./.github/workflows/update_readme.py
